export const outsideBrokerageOptions = [
    { label: '3iQ', value: '3iQ' },
    {
        label: 'A.F.T. Trivest Management Inc.',
        value: 'A.F.T. Trivest Management Inc.',
    },
    { label: 'ABC Funds', value: 'ABC Funds' },
    { label: 'AcceleRate Financial', value: 'AcceleRate Financial' },
    { label: 'Access Credit Union', value: 'Access Credit Union' },
    {
        label: 'Accilent Capital Management Inc.',
        value: 'Accilent Capital Management Inc.',
    },
    { label: 'Achieva Financial', value: 'Achieva Financial' },
    {
        label: 'Acker Finley Asset Management Inc.',
        value: 'Acker Finley Asset Management Inc.',
    },
    { label: 'Acker Finley Inc.', value: 'Acker Finley Inc.' },
    { label: 'Acumen Capital', value: 'Acumen Capital' },
    {
        label: 'ADVANCE SAVINGS CREDIT UNION',
        value: 'ADVANCE SAVINGS CREDIT UNION',
    },
    {
        label: 'AFBS - ACTRA Fraternal Benefit Society',
        value: 'AFBS - ACTRA Fraternal Benefit Society',
    },
    {
        label: 'AFINA Capital Management Inc.',
        value: 'AFINA Capital Management Inc.',
    },
    { label: 'AGF Investments', value: 'AGF Investments' },
    { label: 'AGF Securities Inc.', value: 'AGF Securities Inc.' },
    { label: 'Agilith Capital Inc.', value: 'Agilith Capital Inc.' },
    { label: 'AIC Funds', value: 'AIC Funds' },
    { label: 'AIC Segregated Funds', value: 'AIC Segregated Funds' },
    { label: 'Aligned Capital Partners', value: 'Aligned Capital Partners' },
    { label: 'Alize Capital Inc.', value: 'Alize Capital Inc.' },
    {
        label: 'Allard, Allard et Associés Inc.',
        value: 'Allard, Allard et Associés Inc.',
    },
    {
        label: 'Allexium Asset Management Inc.',
        value: 'Allexium Asset Management Inc.',
    },
    {
        label: 'Allvista Investment Management Inc.',
        value: 'Allvista Investment Management Inc.',
    },
    { label: 'AltaCorp Capital Inc.', value: 'AltaCorp Capital Inc.' },
    { label: 'Alterna Savings', value: 'Alterna Savings' },
    { label: 'Altervest Ltd.', value: 'Altervest Ltd.' },
    {
        label: 'Altium Architecture de patrimoine Inc.',
        value: 'Altium Architecture de patrimoine Inc.',
    },
    {
        label: 'American United Life Insurance Company',
        value: 'American United Life Insurance Company',
    },
    {
        label: 'Anchor Pacific Investment Management Corp',
        value: 'Anchor Pacific Investment Management Corp',
    },
    {
        label: 'Antares Investment Management Inc.',
        value: 'Antares Investment Management Inc.',
    },
    {
        label: 'Archer gestion de patrimoine inc',
        value: 'Archer gestion de patrimoine inc',
    },
    { label: 'ARGOSY SECURITIES INC', value: 'ARGOSY SECURITIES INC' },
    { label: 'Arrow Capital Management', value: 'Arrow Capital Management' },
    {
        label: 'Artemis Investment Management Inc.',
        value: 'Artemis Investment Management Inc.',
    },
    { label: 'ARX Capital Inc.', value: 'ARX Capital Inc.' },
    {
        label: 'ASIA - RBC Wealth Management',
        value: 'ASIA - RBC Wealth Management',
    },
    {
        label: 'Assante Capital / DPM Finacial Planning',
        value: 'Assante Capital / DPM Finacial Planning',
    },
    {
        label: 'ASSANTE CAPITAL MANAGEMENT LTD',
        value: 'ASSANTE CAPITAL MANAGEMENT LTD',
    },
    { label: 'Assante Wealth Management', value: 'Assante Wealth Management' },
    { label: 'Assiniboine Credit Union', value: 'Assiniboine Credit Union' },
    { label: 'Assumption Life', value: 'Assumption Life' },
    {
        label: 'AST / CST Trust Company (Canada)',
        value: 'AST / CST Trust Company (Canada)',
    },
    { label: 'ATB Financial', value: 'ATB Financial' },
    {
        label: 'ATB Securities (Investor Services)',
        value: 'ATB Securities (Investor Services)',
    },
    { label: 'ATB Securities Inc.', value: 'ATB Securities Inc.' },
    {
        label: 'Aventine Management Group Inc.',
        value: 'Aventine Management Group Inc.',
    },
    {
        label: 'Avenue Investment Management Inc.',
        value: 'Avenue Investment Management Inc.',
    },
    { label: 'B2B Bank', value: 'B2B Bank' },
    {
        label: 'B2B Bank Financial Services Inc.',
        value: 'B2B Bank Financial Services Inc.',
    },
    {
        label: 'B2B Bank Securities Services Inc.',
        value: 'B2B Bank Securities Services Inc.',
    },
    { label: 'B2B Bank/MRS', value: 'B2B Bank/MRS' },
    { label: 'B2B Dealer Services', value: 'B2B Dealer Services' },
    { label: 'B2B Trust', value: 'B2B Trust' },
    {
        label: 'Bank Audi - United Arab Emirates',
        value: 'Bank Audi - United Arab Emirates',
    },
    { label: 'BANK OF NOVA SCOTIA', value: 'BANK OF NOVA SCOTIA' },
    {
        label: 'Barometer Capital Management Inc.',
        value: 'Barometer Capital Management Inc.',
    },
    {
        label: 'Barrantagh Investment Management',
        value: 'Barrantagh Investment Management',
    },
    { label: 'Barreau Investments Funds', value: 'Barreau Investments Funds' },
    {
        label: 'Baskin Financial Services Inc.',
        value: 'Baskin Financial Services Inc.',
    },
    { label: 'BBS Securities Inc.', value: 'BBS Securities Inc.' },
    { label: 'BCV Asset Management Inc.', value: 'BCV Asset Management Inc.' },
    { label: 'BEACON SECURITIES', value: 'BEACON SECURITIES' },
    { label: 'Beacon Securities Limited', value: 'Beacon Securities Limited' },
    { label: 'Bell Canada Pension Plan', value: 'Bell Canada Pension Plan' },
    {
        label: 'Bellwether Investment Management Inc.',
        value: 'Bellwether Investment Management Inc.',
    },
    {
        label: 'Beutel Goodman & Company Ltd.',
        value: 'Beutel Goodman & Company Ltd.',
    },
    {
        label: 'Beutel goodman and company ltd.',
        value: 'Beutel goodman and company ltd.',
    },
    { label: 'BirchLeaf Investments Inc.', value: 'BirchLeaf Investments Inc.' },
    { label: 'BloombergSen Inc.', value: 'BloombergSen Inc.' },
    {
        label: 'Bluenose Investment Management Inc.',
        value: 'Bluenose Investment Management Inc.',
    },
    {
        label: 'BMG - Bullion Management Services Inc.',
        value: 'BMG - Bullion Management Services Inc.',
    },
    { label: 'BMO Bank of Montreal', value: 'BMO Bank of Montreal' },
    { label: 'BMO Employee - ESOP', value: 'BMO Employee - ESOP' },
    { label: 'BMO Harris Private Banking', value: 'BMO Harris Private Banking' },
    { label: 'BMO Insurance', value: 'BMO Insurance' },
    { label: 'BMO INVESTORLINE', value: 'BMO INVESTORLINE' },
    { label: 'BMO Life Insurance', value: 'BMO Life Insurance' },
    { label: 'BMO Mutual Funds', value: 'BMO Mutual Funds' },
    { label: 'BMO Nesbitt Burns', value: 'BMO Nesbitt Burns' },
    { label: 'BMO Wealth Management', value: 'BMO Wealth Management' },
    { label: 'BNP PARIBAS FRANCE', value: 'BNP PARIBAS FRANCE' },
    {
        label: 'BNY Mellon Wealth Management, Advisory Services, Inc.',
        value: 'BNY Mellon Wealth Management, Advisory Services, Inc.',
    },
    { label: 'Bombardier Pension Plan', value: 'Bombardier Pension Plan' },
    {
        label: 'Botica Financial Group - Capital Management inc.',
        value: 'Botica Financial Group - Capital Management inc.',
    },
    {
        label: 'Brandes Investment Partners',
        value: 'Brandes Investment Partners',
    },
    { label: 'Brant Securities Limited', value: 'Brant Securities Limited' },
    {
        label: 'Bridgeport Asset Management Inc.',
        value: 'Bridgeport Asset Management Inc.',
    },
    { label: 'Bridging finance inc.', value: 'Bridging finance inc.' },
    {
        label: 'Bristol Gate Capital Partners Inc.',
        value: 'Bristol Gate Capital Partners Inc.',
    },
    { label: 'BROADRIDGE USA', value: 'BROADRIDGE USA' },
    { label: 'Brookfield Financial Corp.', value: 'Brookfield Financial Corp.' },
    {
        label: 'Brownstone Asset Management Inc.',
        value: 'Brownstone Asset Management Inc.',
    },
    { label: 'BT Global Growth Inc.', value: 'BT Global Growth Inc.' },
    { label: 'Budros, Ruhlin & Roe Inc.', value: 'Budros, Ruhlin & Roe Inc.' },
    {
        label: 'Bulkley Valley Credit Union',
        value: 'Bulkley Valley Credit Union',
    },
    {
        label: 'Bull Wealth Management Group Inc',
        value: 'Bull Wealth Management Group Inc',
    },
    { label: 'BURGUNDY ASSET MANAGEMENT', value: 'BURGUNDY ASSET MANAGEMENT' },
    { label: 'Bush Associates Ltd.', value: 'Bush Associates Ltd.' },
    {
        label: 'C.I.C BANQUE TRANSATLANTIQUE FRANCE',
        value: 'C.I.C BANQUE TRANSATLANTIQUE FRANCE',
    },
    { label: 'Caisse Desjardins', value: 'Caisse Desjardins' },
    {
        label: 'Caisse Populaire Alliance limitee',
        value: 'Caisse Populaire Alliance limitee',
    },
    {
        label: 'Caldwell Investment Management Ltd.',
        value: 'Caldwell Investment Management Ltd.',
    },
    { label: 'Caldwell Securities', value: 'Caldwell Securities' },
    { label: 'Cambrian Credit Union', value: 'Cambrian Credit Union' },
    {
        label: 'Campbell, Lee & Ross Investment Management Inc.',
        value: 'Campbell, Lee & Ross Investment Management Inc.',
    },
    {
        label: 'Canaccord Genuity Wealth Management',
        value: 'Canaccord Genuity Wealth Management',
    },
    { label: 'Canada Life', value: 'Canada Life' },
    { label: 'Canada Post Pension Plan', value: 'Canada Post Pension Plan' },
    { label: 'Canada Savings Bond', value: 'Canada Savings Bond' },
    {
        label: 'Canadian ShareOwner Investments Inc.',
        value: 'Canadian ShareOwner Investments Inc.',
    },
    { label: 'Canadian Tire Bank', value: 'Canadian Tire Bank' },
    { label: 'Canadian Western Bank', value: 'Canadian Western Bank' },
    { label: 'Canadian Western Trust', value: 'Canadian Western Trust' },
    {
        label: 'Canadian Worker Co-op Federation',
        value: 'Canadian Worker Co-op Federation',
    },
    { label: 'Canoe Financial Funds', value: 'Canoe Financial Funds' },
    {
        label: 'Canso Investment Counsel Ltd.',
        value: 'Canso Investment Counsel Ltd.',
    },
    {
        label: 'Capital Benoit Asset Management Inc',
        value: 'Capital Benoit Asset Management Inc',
    },
    {
        label: 'Capital régional et coopératif Desjardins',
        value: 'Capital régional et coopératif Desjardins',
    },
    {
        label: 'Capstone Capital Management Inc. (f.k.a Covenant Capital)',
        value: 'Capstone Capital Management Inc. (f.k.a Covenant Capital)',
    },
    {
        label: 'Cardinal Capital Management Inc.',
        value: 'Cardinal Capital Management Inc.',
    },
    {
        label: 'Cardinal Point Capital Management Inc.',
        value: 'Cardinal Point Capital Management Inc.',
    },
    { label: 'Carecana management corp', value: 'Carecana management corp' },
    {
        label: 'Cassels Investment Management Inc.',
        value: 'Cassels Investment Management Inc.',
    },
    {
        label: 'CastleBay Wealth Management Inc',
        value: 'CastleBay Wealth Management Inc',
    },
    { label: 'Castlemoore Inc.', value: 'Castlemoore Inc.' },
    {
        label: 'CCQ - Commission de la contruction du Quebec',
        value: 'CCQ - Commission de la contruction du Quebec',
    },
    { label: 'CDSPI FUNDS', value: 'CDSPI FUNDS' },
    { label: 'Caisse Desjardins', value: 'Caisse Desjardins' },
    {
        label: 'Centurion Asset Management Inc.',
        value: 'Centurion Asset Management Inc.',
    },
    { label: 'Century Management', value: 'Century Management' },
    { label: 'CGOV Asset Management', value: 'CGOV Asset Management' },
    { label: 'CHARLES SCHWAB USA', value: 'CHARLES SCHWAB USA' },
    {
        label: "Children's Education Funds inc.",
        value: "Children's Education Funds inc.",
    },
    { label: 'Chinook Financial', value: 'Chinook Financial' },
    {
        label: 'Chippingham Financial Group Ltd.',
        value: 'Chippingham Financial Group Ltd.',
    },
    { label: 'Chronicle Investments Ltd.', value: 'Chronicle Investments Ltd.' },
    { label: 'CI Investments', value: 'CI Investments' },
    { label: 'CI PRIVATE COUNSEL LP', value: 'CI PRIVATE COUNSEL LP' },
    { label: 'CI Private Wealth', value: 'CI Private Wealth' },
    { label: 'CI Sun Wise Funds', value: 'CI Sun Wise Funds' },
    { label: 'CIBC Bank', value: 'CIBC Bank' },
    {
        label: 'CIBC Direct Brokerage (Wood Gundy)',
        value: 'CIBC Direct Brokerage (Wood Gundy)',
    },
    {
        label: 'CIBC Investor Services Inc.',
        value: 'CIBC Investor Services Inc.',
    },
    { label: 'CIBC Investors Edge', value: 'CIBC Investors Edge' },
    { label: 'CIBC Mellon - Funds', value: 'CIBC Mellon - Funds' },
    { label: 'CIBC Mutual Funds', value: 'CIBC Mutual Funds' },
    {
        label: 'CIBC PPS - Personal Portfolio Services',
        value: 'CIBC PPS - Personal Portfolio Services',
    },
    {
        label: 'CIBC Private Investment Counsel',
        value: 'CIBC Private Investment Counsel',
    },
    {
        label: 'CIBC Private wealth management',
        value: 'CIBC Private wealth management',
    },
    { label: 'CIBC Securities Inc.', value: 'CIBC Securities Inc.' },
    { label: 'CIBC World Markets Inc.', value: 'CIBC World Markets Inc.' },
    {
        label: 'Cidel Asset Management Inc. (former Toron)',
        value: 'Cidel Asset Management Inc. (former Toron)',
    },
    {
        label: 'CLAC - Christian Labour Association of Canada',
        value: 'CLAC - Christian Labour Association of Canada',
    },
    { label: 'Clarus Securities Inc.', value: 'Clarus Securities Inc.' },
    {
        label: 'Clearwater Capital Management',
        value: 'Clearwater Capital Management',
    },
    { label: 'Coast Captital', value: 'Coast Captital' },
    {
        label: 'Cockfield Porretti Cunningham Investment Counsel Inc.',
        value: 'Cockfield Porretti Cunningham Investment Counsel Inc.',
    },
    {
        label: 'Coerente Captital Managment Inc.',
        value: 'Coerente Captital Managment Inc.',
    },
    {
        label: 'Coleford Investment Management Ltd.',
        value: 'Coleford Investment Management Ltd.',
    },
    { label: 'Community Trust', value: 'Community Trust' },
    { label: 'Computershare', value: 'Computershare' },
    {
        label: 'Computershare - Private Capital Solutions',
        value: 'Computershare - Private Capital Solutions',
    },
    {
        label: 'Computershare - Trust Company of Canada',
        value: 'Computershare - Trust Company of Canada',
    },
    { label: 'Computershare USA', value: 'Computershare USA' },
    { label: 'Concentra Financial', value: 'Concentra Financial' },
    {
        label: 'Condor Asset Management Inc.',
        value: 'Condor Asset Management Inc.',
    },
    {
        label: 'Connor, Clark & Lunn Investment Ltd.',
        value: 'Connor, Clark & Lunn Investment Ltd.',
    },
    {
        label: 'Connor, Clark & Lunn Private Capital Ltd.',
        value: 'Connor, Clark & Lunn Private Capital Ltd.',
    },
    {
        label: 'Co-operators Life Insurance Company',
        value: 'Co-operators Life Insurance Company',
    },
    {
        label: 'Cornerstone Investment Counsel Ltd.',
        value: 'Cornerstone Investment Counsel Ltd.',
    },
    { label: 'Cote 100', value: 'Cote 100' },
    { label: 'Counsel Portfolio Services', value: 'Counsel Portfolio Services' },
    {
        label: 'Covington Capital Corporation',
        value: 'Covington Capital Corporation',
    },
    { label: 'Cowan Asset Management', value: 'Cowan Asset Management' },
    {
        label: 'Credential Asset Management',
        value: 'Credential Asset Management',
    },
    { label: 'Credential Securities', value: 'Credential Securities' },
    { label: 'Credit Union', value: 'Credit Union' },
    {
        label: 'Crestridge Asset Management Inc.',
        value: 'Crestridge Asset Management Inc.',
    },
    { label: 'Crystal Wealth Management', value: 'Crystal Wealth Management' },
    { label: 'CST CONSULTANTS C.S.T INC', value: 'CST CONSULTANTS C.S.T INC' },
    { label: 'CTI Capital', value: 'CTI Capital' },
    {
        label: 'CUA - Credit Union Atlantic',
        value: 'CUA - Credit Union Atlantic',
    },
    { label: 'Cumberland Associates', value: 'Cumberland Associates' },
    { label: 'Cumberland Private Wealth', value: 'Cumberland Private Wealth' },
    {
        label: 'Cypress Capital Management Ltd.',
        value: 'Cypress Capital Management Ltd.',
    },
    { label: 'Da Vinci Capital', value: 'Da Vinci Capital' },
    { label: 'Danske BANK - Denmark', value: 'Danske BANK - Denmark' },
    { label: 'Davis-Rea Ltd.', value: 'Davis-Rea Ltd.' },
    {
        label: 'DE THOMAS WEALTH MANAGEMENT',
        value: 'DE THOMAS WEALTH MANAGEMENT',
    },
    {
        label: 'Delbrook Capital Advisors Inc.',
        value: 'Delbrook Capital Advisors Inc.',
    },
    {
        label: 'Delphina Asset Management Inc.',
        value: 'Delphina Asset Management Inc.',
    },
    {
        label: 'Desjardins Financial Securities -– Investments',
        value: 'Desjardins Financial Securities -– Investments',
    },
    {
        label: 'Desjardins Financial Services Firm Inc.',
        value: 'Desjardins Financial Services Firm Inc.',
    },
    { label: 'Desjardins Life Insurance', value: 'Desjardins Life Insurance' },
    {
        label: 'Desjardins Online Brokerage',
        value: 'Desjardins Online Brokerage',
    },
    { label: 'Desjardins Securities', value: 'Desjardins Securities' },
    { label: 'Desjardins Trust', value: 'Desjardins Trust' },
    {
        label: 'Desjardins Wealth Management - Private Wealth Management',
        value: 'Desjardins Wealth Management - Private Wealth Management',
    },
    {
        label: 'Desjardins Wealth Management (Investments)',
        value: 'Desjardins Wealth Management (Investments)',
    },
    {
        label: 'Desjardins Wealth Management (Securities)',
        value: 'Desjardins Wealth Management (Securities)',
    },
    {
        label: 'Dixon & Patterson Financial Planning Inc.',
        value: 'Dixon & Patterson Financial Planning Inc.',
    },
    {
        label: 'Dixon Mitchell Investment Counsel Inc.',
        value: 'Dixon Mitchell Investment Counsel Inc.',
    },
    { label: 'Doherty & Associates Ltd.', value: 'Doherty & Associates Ltd.' },
    { label: 'Donations - Foundations', value: 'Donations - Foundations' },
    {
        label: 'Dorchester Wealth Management Company',
        value: 'Dorchester Wealth Management Company',
    },
    { label: 'Dubeau Capital & Co.', value: 'Dubeau Capital & Co.' },
    { label: 'DUCA Credit Union Ltd', value: 'DUCA Credit Union Ltd' },
    { label: 'DUNCAN ROSS', value: 'DUNCAN ROSS' },
    {
        label: 'Dundee Wealth Investment Counsel',
        value: 'Dundee Wealth Investment Counsel',
    },
    { label: 'Dynamic Funds', value: 'Dynamic Funds' },
    { label: 'E*TRADE SECURITIES USA', value: 'E*TRADE SECURITIES USA' },
    {
        label: 'E.M. Smithies & Associates Investment Management Inc.',
        value: 'E.M. Smithies & Associates Investment Management Inc.',
    },
    {
        label: 'Echelon Wealth Partners Inc.',
        value: 'Echelon Wealth Partners Inc.',
    },
    { label: 'Edgecrest Capital', value: 'Edgecrest Capital' },
    {
        label: 'EdgePoint Wealth Management Inc.',
        value: 'EdgePoint Wealth Management Inc.',
    },
    {
        label: 'EDUCATORS FINANCIAL GROUP INC.',
        value: 'EDUCATORS FINANCIAL GROUP INC.',
    },
    { label: 'EDWARD JONES', value: 'EDWARD JONES' },
    { label: 'Effort Trust Company', value: 'Effort Trust Company' },
    { label: 'EFG Bank SA - CH', value: 'EFG Bank SA - CH' },
    { label: 'Emerging Equities Inc.', value: 'Emerging Equities Inc.' },
    { label: 'Empire Life', value: 'Empire Life' },
    {
        label: 'Enriched Investing Incorporated',
        value: 'Enriched Investing Incorporated',
    },
    { label: 'ENVISION FINANCIAL', value: 'ENVISION FINANCIAL' },
    { label: 'Epargne Placements Quebec', value: 'Epargne Placements Quebec' },
    { label: 'Equatex UK', value: 'Equatex UK' },
    { label: 'Equiniti USA', value: 'Equiniti USA' },
    { label: 'Equitable Bank', value: 'Equitable Bank' },
    { label: 'Equitable Life of Canada', value: 'Equitable Life of Canada' },
    { label: 'Equity Associates Inc.', value: 'Equity Associates Inc.' },
    { label: 'Estonian Credit Union', value: 'Estonian Credit Union' },
    {
        label: 'ETF Capital Management Inc.',
        value: 'ETF Capital Management Inc.',
    },
    { label: 'Etrade USA', value: 'Etrade USA' },
    {
        label: 'Ewing Morris & Co. Investment Partners Ltd.',
        value: 'Ewing Morris & Co. Investment Partners Ltd.',
    },
    { label: 'Excel gestion privée', value: 'Excel gestion privée' },
    {
        label: 'Exponent Investment Management Inc.',
        value: 'Exponent Investment Management Inc.',
    },
    {
        label: 'Fairbank Investment Management Ltd.',
        value: 'Fairbank Investment Management Ltd.',
    },
    { label: 'Ferique Management', value: 'Ferique Management' },
    { label: 'FI Capital Ltd.', value: 'FI Capital Ltd.' },
    { label: 'Fidelity Clearing Canada', value: 'Fidelity Clearing Canada' },
    { label: 'Fidelity Investments', value: 'Fidelity Investments' },
    { label: 'Fidelity USA', value: 'Fidelity USA' },
    {
        label: 'Fieldhouse Capital Management Inc.',
        value: 'Fieldhouse Capital Management Inc.',
    },
    {
        label: 'Fiera Capital Funds C/O IDFS',
        value: 'Fiera Capital Funds C/O IDFS',
    },
    { label: 'Fiera Capital Inc.', value: 'Fiera Capital Inc.' },
    {
        label: 'Fiera Investments LP, c/o IFDS',
        value: 'Fiera Investments LP, c/o IFDS',
    },
    { label: 'First Calgary Financial', value: 'First Calgary Financial' },
    {
        label: 'First Island Financial Services Ltd.',
        value: 'First Island Financial Services Ltd.',
    },
    {
        label: 'Fisgard Asset Management Corporation',
        value: 'Fisgard Asset Management Corporation',
    },
    {
        label: 'FMOQ - Fonds des Medecins Omnipraticiens du Quebec',
        value: 'FMOQ - Fonds des Medecins Omnipraticiens du Quebec',
    },
    {
        label: 'Focus Asset Management Ltd.',
        value: 'Focus Asset Management Ltd.',
    },
    {
        label: 'Folger Nolan Fleming Douglas USA',
        value: 'Folger Nolan Fleming Douglas USA',
    },
    { label: 'Fondaction CSN', value: 'Fondaction CSN' },
    { label: 'FONDATION UNIVERSITAS', value: 'FONDATION UNIVERSITAS' },
    {
        label: 'Foresters Asset Management Inc.',
        value: 'Foresters Asset Management Inc.',
    },
    { label: 'Formula Growth Ltd.', value: 'Formula Growth Ltd.' },
    {
        label: 'Forstrong Global Asset Management Inc.',
        value: 'Forstrong Global Asset Management Inc.',
    },
    { label: 'Foster & Associates', value: 'Foster & Associates' },
    { label: 'Foyston, Gordon & Payne', value: 'Foyston, Gordon & Payne' },
    {
        label: 'Franklin Templeton Investments',
        value: 'Franklin Templeton Investments',
    },
    {
        label: 'Friedberg Mercantile Group Ltd.',
        value: 'Friedberg Mercantile Group Ltd.',
    },
    { label: 'Frontwater Capital Inc.', value: 'Frontwater Capital Inc.' },
    {
        label: 'FTC - Fiduciary Trust Company of Canada',
        value: 'FTC - Fiduciary Trust Company of Canada',
    },
    { label: 'FTQ - Fonds de Solidarite', value: 'FTQ - Fonds de Solidarite' },
    { label: 'Fundex Investments', value: 'Fundex Investments' },
    { label: 'G & F FINANCIAL', value: 'G & F FINANCIAL' },
    {
        label: 'Galileo Equity Management Inc.',
        value: 'Galileo Equity Management Inc.',
    },
    { label: 'Galliant Advisors LP', value: 'Galliant Advisors LP' },
    {
        label: 'Genbridge Family Offices Inc.',
        value: 'Genbridge Family Offices Inc.',
    },
    { label: 'General Bank of Canada', value: 'General Bank of Canada' },
    {
        label: 'Generation Portfolio Management Corp.',
        value: 'Generation Portfolio Management Corp.',
    },
    {
        label: 'GENn Investment Counsel Ltd',
        value: 'GENn Investment Counsel Ltd',
    },
    { label: 'Genova Private Management', value: 'Genova Private Management' },
    {
        label: 'GENUS CAPITAL MANAGEMENT INC.',
        value: 'GENUS CAPITAL MANAGEMENT INC.',
    },
    {
        label: 'Georgian Capital Partners Corp.',
        value: 'Georgian Capital Partners Corp.',
    },
    {
        label: "Gestion d'actif Stanton (Stanton Asset Management)",
        value: "Gestion d'actif Stanton (Stanton Asset Management)",
    },
    {
        label: 'Gestion de portefeuille stratégique Medici Inc.',
        value: 'Gestion de portefeuille stratégique Medici Inc.',
    },
    { label: 'Gestion Privée Diamant', value: 'Gestion Privée Diamant' },
    { label: 'Gestion Privée Phœnix S.A.', value: 'Gestion Privée Phœnix S.A.' },
    { label: 'GF Securities Canada', value: 'GF Securities Canada' },
    {
        label: 'GFI Investment Counsel Ltd.',
        value: 'GFI Investment Counsel Ltd.',
    },
    { label: 'Giverny Capital Inc.', value: 'Giverny Capital Inc.' },
    { label: 'Global Maxfin Capital Inc.', value: 'Global Maxfin Capital Inc.' },
    {
        label: 'Global Maxfin Investment Inc.',
        value: 'Global Maxfin Investment Inc.',
    },
    { label: 'Global Securities', value: 'Global Securities' },
    { label: 'Globevest Capital Inc.', value: 'Globevest Capital Inc.' },
    { label: 'GLUSKIN SHEFF ASSOCIATES', value: 'GLUSKIN SHEFF ASSOCIATES' },
    { label: 'GMG Private Counsel', value: 'GMG Private Counsel' },
    { label: 'GMP FirstEnergy', value: 'GMP FirstEnergy' },
    {
        label: 'Gold Investment Management Ltd.',
        value: 'Gold Investment Management Ltd.',
    },
    { label: 'Golden Opportunities Fund', value: 'Golden Opportunities Fund' },
    {
        label: 'Goodman and Company Investments Counsel Inc.',
        value: 'Goodman and Company Investments Counsel Inc.',
    },
    {
        label: 'Goodreid Investment Counsel',
        value: 'Goodreid Investment Counsel',
    },
    { label: 'Goodwood Inc.', value: 'Goodwood Inc.' },
    { label: 'Government of Canada', value: 'Government of Canada' },
    { label: 'Gravitas Securities Inc.', value: 'Gravitas Securities Inc.' },
    {
        label: 'Grayhawk Investment Strategies Inc',
        value: 'Grayhawk Investment Strategies Inc',
    },
    {
        label: 'Great West Life - Assurance Company',
        value: 'Great West Life - Assurance Company',
    },
    {
        label: 'Greenrock Capital Partners Inc.',
        value: 'Greenrock Capital Partners Inc.',
    },
    {
        label: 'Greenskeeper Asset Management Inc.',
        value: 'Greenskeeper Asset Management Inc.',
    },
    {
        label: 'Greystone Managed Investments Inc.',
        value: 'Greystone Managed Investments Inc.',
    },
    { label: 'Groupe Cloutier', value: 'Groupe Cloutier' },
    { label: 'Growth Works Capital Funds', value: 'Growth Works Capital Funds' },
    { label: 'Growthquest Capital Inc.', value: 'Growthquest Capital Inc.' },
    {
        label: 'Guardian Capital Advisors LP',
        value: 'Guardian Capital Advisors LP',
    },
    { label: 'GWP Wealth Management Inc.', value: 'GWP Wealth Management Inc.' },
    { label: 'Hampton Securities Ltd.', value: 'Hampton Securities Ltd.' },
    { label: 'Hang Seng Bank - Hong Kong', value: 'Hang Seng Bank - Hong Kong' },
    {
        label: 'Harbourfront Wealth Management Inc.',
        value: 'Harbourfront Wealth Management Inc.',
    },
    { label: 'Harmony Funds', value: 'Harmony Funds' },
    { label: 'Harris, Bolduc Associates', value: 'Harris, Bolduc Associates' },
    { label: 'HAYWOOD SECURITIES', value: 'HAYWOOD SECURITIES' },
    {
        label: 'Headsail Wealth Management Inc.',
        value: 'Headsail Wealth Management Inc.',
    },
    {
        label: 'Heathbridge Capital Management Ltd.',
        value: 'Heathbridge Capital Management Ltd.',
    },
    {
        label: 'Hemisphere Capital Management Inc.',
        value: 'Hemisphere Capital Management Inc.',
    },
    { label: 'Henley Capital Corporation', value: 'Henley Capital Corporation' },
    {
        label: 'Heritage Education Funds Inc.',
        value: 'Heritage Education Funds Inc.',
    },
    {
        label: 'Heritage Yorkville Mutual Funds',
        value: 'Heritage Yorkville Mutual Funds',
    },
    {
        label: 'Heward Investment Management Inc.',
        value: 'Heward Investment Management Inc.',
    },
    {
        label: 'Higgins Investment Group Inc.',
        value: 'Higgins Investment Group Inc.',
    },
    {
        label: 'Highstreet Asset Management Inc.',
        value: 'Highstreet Asset Management Inc.',
    },
    {
        label: 'Hillsdale Investment Management Inc.',
        value: 'Hillsdale Investment Management Inc.',
    },
    {
        label: 'HNB - Anchor Investment Management Inc.',
        value: 'HNB - Anchor Investment Management Inc.',
    },
    { label: 'HNW Management Inc.', value: 'HNW Management Inc.' },
    { label: 'Hollis Wealth', value: 'Hollis Wealth' },
    { label: 'Home Trust Company', value: 'Home Trust Company' },
    { label: 'HOOPP Pension Center', value: 'HOOPP Pension Center' },
    {
        label: 'Howard, Barclay Associates Ltd.',
        value: 'Howard, Barclay Associates Ltd.',
    },
    { label: 'HSBC', value: 'HSBC' },
    { label: 'HSBC Private Wealth', value: 'HSBC Private Wealth' },
    { label: 'HSBC Securities', value: 'HSBC Securities' },
    { label: 'HUB CAPITAL FINANCIAL', value: 'HUB CAPITAL FINANCIAL' },
    {
        label: 'Hughes Little Investment Management Ltd.',
        value: 'Hughes Little Investment Management Ltd.',
    },
    {
        label: 'IA - Industrial Alliance Financial Group (Insurance)',
        value: 'IA - Industrial Alliance Financial Group (Insurance)',
    },
    {
        label: 'IA - Industrielle Alliance Securities (IAS)',
        value: 'IA - Industrielle Alliance Securities (IAS)',
    },
    { label: 'IA - Investia Financial', value: 'IA - Investia Financial' },
    { label: 'IA Clarington Investments', value: 'IA Clarington Investments' },
    {
        label: 'IceCap Asset Management Limited',
        value: 'IceCap Asset Management Limited',
    },
    { label: 'ICICI Bank Canada', value: 'ICICI Bank Canada' },
    {
        label: 'IEPP Investment Management Inc.',
        value: 'IEPP Investment Management Inc.',
    },
    { label: 'IG Wealth management', value: 'IG Wealth management' },
    { label: 'IGM Financial', value: 'IGM Financial' },
    { label: 'InfiniT', value: 'InfiniT' },
    { label: 'INFOR Financial Inc.', value: 'INFOR Financial Inc.' },
    { label: 'ING Direct', value: 'ING Direct' },
    {
        label: 'Integral Wealth Securities Limited',
        value: 'Integral Wealth Securities Limited',
    },
    {
        label: 'Interactive Brokers Canada Inc.',
        value: 'Interactive Brokers Canada Inc.',
    },
    {
        label: 'Interior Savings Credit Union',
        value: 'Interior Savings Credit Union',
    },
    {
        label: 'Inukshuk Capital Management Inc.',
        value: 'Inukshuk Capital Management Inc.',
    },
    { label: 'Inverlochy Capital Ltd.', value: 'Inverlochy Capital Ltd.' },
    {
        label: 'Invesco Funds (AIM Trimark)',
        value: 'Invesco Funds (AIM Trimark)',
    },
    { label: 'Investax Management Inc.', value: 'Investax Management Inc.' },
    {
        label: 'Investment Planning Counsel - Investment Corp.',
        value: 'Investment Planning Counsel - Investment Corp.',
    },
    {
        label: 'Investment Planning Counsel - Securities Corp.',
        value: 'Investment Planning Counsel - Securities Corp.',
    },
    { label: 'Investment Strategies Inc.', value: 'Investment Strategies Inc.' },
    { label: 'Investors Group', value: 'Investors Group' },
    {
        label: 'Investors Group Financial Services',
        value: 'Investors Group Financial Services',
    },
    {
        label: 'Investors Group Securities Inc',
        value: 'Investors Group Securities Inc',
    },
    { label: 'IVARI (Transamerica Life)', value: 'IVARI (Transamerica Life)' },
    {
        label: 'J Priest Investment Management',
        value: 'J Priest Investment Management',
    },
    {
        label: 'J.C. Hood Investment Counsel',
        value: 'J.C. Hood Investment Counsel',
    },
    { label: 'J.P. Morgan USA', value: 'J.P. Morgan USA' },
    { label: 'Jacob Securities Inc.', value: 'Jacob Securities Inc.' },
    { label: 'Japa International Ltd.', value: 'Japa International Ltd.' },
    { label: 'Jarislowsky Fraser Limited', value: 'Jarislowsky Fraser Limited' },
    { label: 'JC Clark Ltd.', value: 'JC Clark Ltd.' },
    { label: 'Jefferies Securities Inc.', value: 'Jefferies Securities Inc.' },
    { label: 'JitneyTrade Inc.', value: 'JitneyTrade Inc.' },
    {
        label: 'John S. Keenlyside Company Ltd.',
        value: 'John S. Keenlyside Company Ltd.',
    },
    {
        label: 'Jones Collombin Investment Counsel Inc.',
        value: 'Jones Collombin Investment Counsel Inc.',
    },
    {
        label: 'Kassirer Asset Management Corporation',
        value: 'Kassirer Asset Management Corporation',
    },
    { label: 'Kawartha Credit Union', value: 'Kawartha Credit Union' },
    {
        label: 'KCM Wealth Management Inc. (acquired by LYCOS)',
        value: 'KCM Wealth Management Inc. (acquired by LYCOS)',
    },
    { label: 'Kernaghan Partners LTD.', value: 'Kernaghan Partners LTD.' },
    {
        label: 'Kerr Financial Advisors Inc.',
        value: 'Kerr Financial Advisors Inc.',
    },
    { label: 'Keybase Financial Group', value: 'Keybase Financial Group' },
    {
        label: 'Kilburn Ogilvie Waymann Investment Management Ltd.',
        value: 'Kilburn Ogilvie Waymann Investment Management Ltd.',
    },
    { label: 'Kingsdale Capital Inc.', value: 'Kingsdale Capital Inc.' },
    { label: 'Kingwest Company', value: 'Kingwest Company' },
    { label: 'KJ Harrison Partners Inc.', value: 'KJ Harrison Partners Inc.' },
    { label: 'KNIGHTS OF COLUMBUS', value: 'KNIGHTS OF COLUMBUS' },
    { label: 'KNIGHTS OF COLUMBUS USA', value: 'KNIGHTS OF COLUMBUS USA' },
    { label: 'Knowledge First Financial', value: 'Knowledge First Financial' },
    { label: 'La Capitale', value: 'La Capitale' },
    { label: 'Lakeshore Securities', value: 'Lakeshore Securities' },
    {
        label: 'Landry Investment Management Inc.',
        value: 'Landry Investment Management Inc.',
    },
    { label: 'Laurentian Bank', value: 'Laurentian Bank' },
    {
        label: 'Laurentian Bank Discount Brokerage',
        value: 'Laurentian Bank Discount Brokerage',
    },
    { label: 'Laurentian Bank Securities', value: 'Laurentian Bank Securities' },
    {
        label: 'Laurus Investment Counseling',
        value: 'Laurus Investment Counseling',
    },
    { label: 'LBC Financial Services', value: 'LBC Financial Services' },
    { label: 'LDIC Inc.', value: 'LDIC Inc.' },
    { label: 'Leede Financial', value: 'Leede Financial' },
    { label: 'Leede Jones Gable inc.', value: 'Leede Jones Gable inc.' },
    {
        label: 'Legacy Investment Services, Inc.',
        value: 'Legacy Investment Services, Inc.',
    },
    {
        label: 'Leith Wheeler Investment Counsel Ltd.',
        value: 'Leith Wheeler Investment Counsel Ltd.',
    },
    {
        label: 'Leon Frazer Associates Inc.',
        value: 'Leon Frazer Associates Inc.',
    },
    {
        label: 'Les Investissements Rivemont Inc.',
        value: 'Les Investissements Rivemont Inc.',
    },
    { label: 'Lester Asset Management', value: 'Lester Asset Management' },
    {
        label: 'LETKO, BROSSEAU ASSOCIATES INC',
        value: 'LETKO, BROSSEAU ASSOCIATES INC',
    },
    {
        label: 'Level 3 Investment Management Inc.',
        value: 'Level 3 Investment Management Inc.',
    },
    {
        label: 'Lewin Capital Management Ltd.',
        value: 'Lewin Capital Management Ltd.',
    },
    {
        label: 'Liberty International Investment Management Inc.',
        value: 'Liberty International Investment Management Inc.',
    },
    { label: 'Lifewealth Inc.', value: 'Lifewealth Inc.' },
    { label: 'Lightwater Partners Ltd.', value: 'Lightwater Partners Ltd.' },
    { label: 'LIGHTYEAR CAPITAL INC', value: 'LIGHTYEAR CAPITAL INC' },
    { label: 'Linde Equity Inc.', value: 'Linde Equity Inc.' },
    {
        label: 'Lionguard Capital Management Inc.',
        value: 'Lionguard Capital Management Inc.',
    },
    {
        label: 'Lionridge Capital Management Inc.',
        value: 'Lionridge Capital Management Inc.',
    },
    { label: 'Liquidnet Canada Inc.', value: 'Liquidnet Canada Inc.' },
    {
        label: 'Lissom Investment Management Inc.',
        value: 'Lissom Investment Management Inc.',
    },
    {
        label: 'Local Authorities Pension Plan',
        value: 'Local Authorities Pension Plan',
    },
    {
        label: 'Logan Wealth Management Inc.',
        value: 'Logan Wealth Management Inc.',
    },
    { label: 'London Life', value: 'London Life' },
    {
        label: 'Longview Asset Management Ltd.',
        value: 'Longview Asset Management Ltd.',
    },
    {
        label: 'Lorica Investment Counsel Inc.',
        value: 'Lorica Investment Counsel Inc.',
    },
    {
        label: 'Lorne Steinberg Wealth Management Inc.',
        value: 'Lorne Steinberg Wealth Management Inc.',
    },
    {
        label: 'Louisbourg investments - Institutional Management',
        value: 'Louisbourg investments - Institutional Management',
    },
    {
        label: 'Louisbourg Investments - Private Wealth Management',
        value: 'Louisbourg Investments - Private Wealth Management',
    },
    {
        label: 'Lycos Asset Management Inc.',
        value: 'Lycos Asset Management Inc.',
    },
    {
        label: 'Lyons Asset Management Inc.',
        value: 'Lyons Asset Management Inc.',
    },
    { label: 'M Partners', value: 'M Partners' },
    {
        label: 'M.S. Lamont and Associates Ltd.',
        value: 'M.S. Lamont and Associates Ltd.',
    },
    {
        label: 'Mackenzie Financial (Mutual Funds)',
        value: 'Mackenzie Financial (Mutual Funds)',
    },
    { label: 'Mackie Research Capital', value: 'Mackie Research Capital' },
    {
        label: 'MacNicol Associates Asset Management',
        value: 'MacNicol Associates Asset Management',
    },
    { label: 'MACQUARIE', value: 'MACQUARIE' },
    {
        label: 'Mahogany Asset Management Inc.',
        value: 'Mahogany Asset Management Inc.',
    },
    {
        label: 'Majestic Asset Management LLC',
        value: 'Majestic Asset Management LLC',
    },
    {
        label: 'Mandeville Private Client Inc.',
        value: 'Mandeville Private Client Inc.',
    },
    {
        label: 'Manitou Investment Management Ltd.',
        value: 'Manitou Investment Management Ltd.',
    },
    {
        label: 'Manulife (Groupe Retirement)',
        value: 'Manulife (Groupe Retirement)',
    },
    { label: 'Manulife Bank', value: 'Manulife Bank' },
    { label: 'Manulife Financial', value: 'Manulife Financial' },
    { label: 'Manulife Investments', value: 'Manulife Investments' },
    { label: 'Manulife Securities', value: 'Manulife Securities' },
    {
        label: 'Manulife Securities Investment Services Inc.',
        value: 'Manulife Securities Investment Services Inc.',
    },
    {
        label: 'Maplewest Capital Corporation',
        value: 'Maplewest Capital Corporation',
    },
    {
        label: 'Marquest asset management inc.',
        value: 'Marquest asset management inc.',
    },
    {
        label: 'Marret Asset Management Inc.',
        value: 'Marret Asset Management Inc.',
    },
    { label: 'Martin, Lucas Seagram Ltd.', value: 'Martin, Lucas Seagram Ltd.' },
    { label: 'Matco financial inc', value: 'Matco financial inc' },
    { label: 'Matco Financial Inc.', value: 'Matco Financial Inc.' },
    { label: 'Mawer Direct Investing LTD', value: 'Mawer Direct Investing LTD' },
    {
        label: 'Mawer Investment Management Ltd. - Funds',
        value: 'Mawer Investment Management Ltd. - Funds',
    },
    { label: 'MCAN Mortgage Corporation', value: 'MCAN Mortgage Corporation' },
    {
        label: 'McLean Partners Wealth Management',
        value: 'McLean Partners Wealth Management',
    },
    { label: 'MD Financial Management', value: 'MD Financial Management' },
    { label: 'MD Management Brokerage', value: 'MD Management Brokerage' },
    {
        label: 'Meckelborg Financial Group Ltd.',
        value: 'Meckelborg Financial Group Ltd.',
    },
    { label: 'MERICI FIANCIAL SERVICES', value: 'MERICI FIANCIAL SERVICES' },
    { label: 'Meridian Credit Union', value: 'Meridian Credit Union' },
    { label: 'Merrill Lynch USA', value: 'Merrill Lynch USA' },
    { label: 'MICA CAPITAL', value: 'MICA CAPITAL' },
    { label: 'Middle Field Group - funds', value: 'Middle Field Group - funds' },
    {
        label: 'Milestone Investment Counsel Inc.',
        value: 'Milestone Investment Counsel Inc.',
    },
    {
        label: 'Millar Private Wealth Management Inc.',
        value: 'Millar Private Wealth Management Inc.',
    },
    { label: 'Mirabaud', value: 'Mirabaud' },
    { label: 'MIRABAUD CANADA INC.', value: 'MIRABAUD CANADA INC.' },
    { label: 'Monarch Wealth Corporation', value: 'Monarch Wealth Corporation' },
    { label: 'MONEY BLOCK USA', value: 'MONEY BLOCK USA' },
    { label: 'Montag Private Wealth Inc.', value: 'Montag Private Wealth Inc.' },
    {
        label: 'Morgan Meighen Associates Ltd.',
        value: 'Morgan Meighen Associates Ltd.',
    },
    { label: 'Morgan Stanley Canada', value: 'Morgan Stanley Canada' },
    { label: 'Morgan Stanley USA', value: 'Morgan Stanley USA' },
    { label: 'Morneau Shepell', value: 'Morneau Shepell' },
    { label: 'Most QC Portfolios', value: 'Most QC Portfolios' },
    { label: 'MRS INC.', value: 'MRS INC.' },
    { label: 'National Bank Financial', value: 'National Bank Financial' },
    { label: 'National Bank Insurance', value: 'National Bank Insurance' },
    {
        label: 'NATIXIS INTERÉPARGNE SERVICE',
        value: 'NATIXIS INTERÉPARGNE SERVICE',
    },
    {
        label: 'NBC - National Bank of Canada',
        value: 'NBC - National Bank of Canada',
    },
    {
        label: 'NBDB - National Bank Direct Brokerage',
        value: 'NBDB - National Bank Direct Brokerage',
    },
    {
        label: 'NBI - National Bank Investements',
        value: 'NBI - National Bank Investements',
    },
    { label: 'NBT - National Bank Trust', value: 'NBT - National Bank Trust' },
    { label: 'NCM Investments', value: 'NCM Investments' },
    {
        label: 'NCP Investment Management Inc.',
        value: 'NCP Investment Management Inc.',
    },
    {
        label: 'NEI - Northwest Mutual Funds',
        value: 'NEI - Northwest Mutual Funds',
    },
    {
        label: 'Nelson District Credit Union',
        value: 'Nelson District Credit Union',
    },
    {
        label: 'Nest Wealth Asset Management Inc.',
        value: 'Nest Wealth Asset Management Inc.',
    },
    {
        label: 'Newhaven Asset Management Inc.',
        value: 'Newhaven Asset Management Inc.',
    },
    {
        label: 'Newport Private Wealth Management Inc.',
        value: 'Newport Private Wealth Management Inc.',
    },
    { label: 'Next Edge Capital Corp.', value: 'Next Edge Capital Corp.' },
    { label: 'Nicola Wealth Management', value: 'Nicola Wealth Management' },
    { label: 'Ninepoint Partners LP', value: 'Ninepoint Partners LP' },
    {
        label: 'Norrep Capital Management Ltd.',
        value: 'Norrep Capital Management Ltd.',
    },
    {
        label: 'Nortel Networks Pension Plan',
        value: 'Nortel Networks Pension Plan',
    },
    { label: 'North Growth Management', value: 'North Growth Management' },
    { label: 'North Shore Credit Union', value: 'North Shore Credit Union' },
    {
        label: 'Northland Wealth Management Inc.',
        value: 'Northland Wealth Management Inc.',
    },
    {
        label: 'Northwood Private Counsel Inc.',
        value: 'Northwood Private Counsel Inc.',
    },
    { label: 'Oaken Financial', value: 'Oaken Financial' },
    { label: 'Odlum Brown', value: 'Odlum Brown' },
    { label: 'Olympia Trust Company', value: 'Olympia Trust Company' },
    { label: 'OMG Wealth Management Ltd.', value: 'OMG Wealth Management Ltd.' },
    { label: 'Omnivita Custom Wealth', value: 'Omnivita Custom Wealth' },
    { label: 'One Capital Management', value: 'One Capital Management' },
    { label: 'Open Access', value: 'Open Access' },
    { label: 'Optimize Wealth Management', value: 'Optimize Wealth Management' },
    { label: 'Optimum Asset Management', value: 'Optimum Asset Management' },
    { label: 'Outlook Financial', value: 'Outlook Financial' },
    {
        label: 'Overseas Financial institutions',
        value: 'Overseas Financial institutions',
    },
    {
        label: 'Pacific International Financial (PI Financial)',
        value: 'Pacific International Financial (PI Financial)',
    },
    {
        label: 'Pacific Spirit Investment Management Inc.',
        value: 'Pacific Spirit Investment Management Inc.',
    },
    { label: 'Pacifica Partners Inc.', value: 'Pacifica Partners Inc.' },
    {
        label: 'Padlock Investment Management Inc.',
        value: 'Padlock Investment Management Inc.',
    },
    {
        label: 'Pallas Athena Investment Counsel',
        value: 'Pallas Athena Investment Counsel',
    },
    { label: 'Palos Management Inc.', value: 'Palos Management Inc.' },
    {
        label: 'Pangaea Asset Management Inc.',
        value: 'Pangaea Asset Management Inc.',
    },
    { label: 'Paradigm Capital', value: 'Paradigm Capital' },
    {
        label: 'Paragon Private Wealth Inc.',
        value: 'Paragon Private Wealth Inc.',
    },
    {
        label: 'Park Capital Management (2012) Inc.',
        value: 'Park Capital Management (2012) Inc.',
    },
    {
        label: "Patrimonica Gestion d'actifs inc.",
        value: "Patrimonica Gestion d'actifs inc.",
    },
    {
        label: 'Pavilion Advisory Group Ltd.',
        value: 'Pavilion Advisory Group Ltd.',
    },
    {
        label: 'Pavilion Global Markets Ltd.',
        value: 'Pavilion Global Markets Ltd.',
    },
    { label: 'PEAK Investment Services', value: 'PEAK Investment Services' },
    { label: 'PEAK Securities', value: 'PEAK Securities' },
    {
        label: 'Pembroke Private Wealth Management',
        value: 'Pembroke Private Wealth Management',
    },
    { label: 'Pension RRUQ', value: 'Pension RRUQ' },
    { label: 'Pension RTC', value: 'Pension RTC' },
    { label: 'PENSIONS', value: 'PENSIONS' },
    { label: 'Peoples Trust', value: 'Peoples Trust' },
    { label: 'Perennial Asset Management', value: 'Perennial Asset Management' },
    { label: 'Perimeter Markets Inc.', value: 'Perimeter Markets Inc.' },
    {
        label: 'Perron Partners Wealth Management Corp.',
        value: 'Perron Partners Wealth Management Corp.',
    },
    { label: 'Perry Securities LTD.', value: 'Perry Securities LTD.' },
    { label: 'Pershing USA', value: 'Pershing USA' },
    { label: 'Peters Co. Limited', value: 'Peters Co. Limited' },
    { label: 'PFSL Investments', value: 'PFSL Investments' },
    { label: 'Phillips Hagar North (PHN)', value: 'Phillips Hagar North (PHN)' },
    { label: 'Placements Louis Journault', value: 'Placements Louis Journault' },
    {
        label: 'PNC WEALTH MANAGEMENT - USA',
        value: 'PNC WEALTH MANAGEMENT - USA',
    },
    {
        label: 'Polar Asset Management Partners Inc.',
        value: 'Polar Asset Management Partners Inc.',
    },
    { label: 'Polaris Financial Inc.', value: 'Polaris Financial Inc.' },
    { label: 'Pollitt Co. Inc.', value: 'Pollitt Co. Inc.' },
    {
        label: 'Pollitt Investment Counsel Inc.',
        value: 'Pollitt Investment Counsel Inc.',
    },
    {
        label: 'Portfolio Management Corporation',
        value: 'Portfolio Management Corporation',
    },
    { label: 'Portfolio Stewards Inc.', value: 'Portfolio Stewards Inc.' },
    {
        label: 'Portfolio Strategies Corporation',
        value: 'Portfolio Strategies Corporation',
    },
    { label: 'Prefontaine Capital Inc.', value: 'Prefontaine Capital Inc.' },
    { label: 'Prime Quadrant LP', value: 'Prime Quadrant LP' },
    { label: 'Primerica', value: 'Primerica' },
    { label: 'Professionals Financial', value: 'Professionals Financial' },
    { label: "Professional's Financial", value: "Professional's Financial" },
    {
        label: 'Professionals Financial Funds',
        value: 'Professionals Financial Funds',
    },
    { label: 'Pugsley Capital Inc.', value: 'Pugsley Capital Inc.' },
    { label: 'Purpose Investments Inc.', value: 'Purpose Investments Inc.' },
    { label: 'PWL Capital INC.', value: 'PWL Capital INC.' },
    {
        label: 'Qtrade Asset Management Inc',
        value: 'Qtrade Asset Management Inc',
    },
    { label: 'Qtrade Investor', value: 'Qtrade Investor' },
    { label: 'Quadrus Invesments', value: 'Quadrus Invesments' },
    {
        label: 'QUBE Investment Management Inc.',
        value: 'QUBE Investment Management Inc.',
    },
    { label: 'Queensbury securities inc', value: 'Queensbury securities inc' },
    { label: 'Questrade', value: 'Questrade' },
    { label: 'QV Investors Inc.', value: 'QV Investors Inc.' },
    {
        label: 'QVO VADIS Investment Management Inc.',
        value: 'QVO VADIS Investment Management Inc.',
    },
    {
        label: 'R.E.G.A.R. Gestion Privee Inc.',
        value: 'R.E.G.A.R. Gestion Privee Inc.',
    },
    {
        label: 'Rae Lipskie Investment Counsel Inc.',
        value: 'Rae Lipskie Investment Counsel Inc.',
    },
    { label: 'Raintree Asset Management', value: 'Raintree Asset Management' },
    { label: 'Raymond James', value: 'Raymond James' },
    { label: 'Raymond James USA', value: 'Raymond James USA' },
    { label: 'RBC Dexia', value: 'RBC Dexia' },
    { label: 'RBC Direct Investing', value: 'RBC Direct Investing' },
    { label: 'RBC Dominion Securities', value: 'RBC Dominion Securities' },
    { label: 'RBC LIFE INSURANCE', value: 'RBC LIFE INSURANCE' },
    {
        label: 'RBC LIFE INSURANCE SEGRETATED FUNDS',
        value: 'RBC LIFE INSURANCE SEGRETATED FUNDS',
    },
    { label: 'RBC Private Counsel USA', value: 'RBC Private Counsel USA' },
    { label: 'RBC Royal Bank Funds', value: 'RBC Royal Bank Funds' },
    { label: 'RBC Royal Bank of Canada', value: 'RBC Royal Bank of Canada' },
    {
        label: 'RBC Royal Bank of Canada - RMFI',
        value: 'RBC Royal Bank of Canada - RMFI',
    },
    { label: 'RBC ROYAL TRUST', value: 'RBC ROYAL TRUST' },
    { label: 'RBC Wealth Management', value: 'RBC Wealth Management' },
    { label: 'RealCap Holdings Ltd.', value: 'RealCap Holdings Ltd.' },
    { label: 'Reciever General of Canada', value: 'Reciever General of Canada' },
    {
        label: 'Rempart Asset Management Inc.',
        value: 'Rempart Asset Management Inc.',
    },
    {
        label: 'Renaissance Investments / CIBC Asset Management Inc.',
        value: 'Renaissance Investments / CIBC Asset Management Inc.',
    },
    {
        label: 'Retraite Quebec (CARRA RRQ)',
        value: 'Retraite Quebec (CARRA RRQ)',
    },
    {
        label: 'RGF Integrated Wealth Management',
        value: 'RGF Integrated Wealth Management',
    },
    { label: 'Richardson GMP Securities', value: 'Richardson GMP Securities' },
    { label: 'RN Croft Financial Inc.', value: 'RN Croft Financial Inc.' },
    {
        label: 'Robert Evans Investment Counsel Limited',
        value: 'Robert Evans Investment Counsel Limited',
    },
    {
        label: 'Rocklinc Investment Partners Inc.',
        value: 'Rocklinc Investment Partners Inc.',
    },
    {
        label: 'Rockvale (Stonebrooke) Capital Management Inc.',
        value: 'Rockvale (Stonebrooke) Capital Management Inc.',
    },
    { label: 'Rogers Group Financial', value: 'Rogers Group Financial' },
    { label: 'ROI Capital', value: 'ROI Capital' },
    {
        label: 'ROMSPEN MORTGAGE INVESTMENT FUND',
        value: 'ROMSPEN MORTGAGE INVESTMENT FUND',
    },
    { label: 'Rosen Partnership Inc.', value: 'Rosen Partnership Inc.' },
    { label: 'Rothenberg Rothenberg', value: 'Rothenberg Rothenberg' },
    {
        label: 'Rothenberg Capital Management',
        value: 'Rothenberg Capital Management',
    },
    {
        label: 'RPIA - Global fixed income experts',
        value: 'RPIA - Global fixed income experts',
    },
    {
        label: 'Russell Investments Canada Ltd.',
        value: 'Russell Investments Canada Ltd.',
    },
    { label: 'Saskworks Venture Fund', value: 'Saskworks Venture Fund' },
    {
        label: 'Schwaben Capital Group Ltd.',
        value: 'Schwaben Capital Group Ltd.',
    },
    { label: 'Scotia Bank', value: 'Scotia Bank' },
    { label: 'Scotia Capital', value: 'Scotia Capital' },
    { label: 'Scotia iTrade', value: 'Scotia iTrade' },
    { label: 'Scotia McLeod', value: 'Scotia McLeod' },
    {
        label: 'Scotia Mortgage Corporation',
        value: 'Scotia Mortgage Corporation',
    },
    {
        label: 'Scotia Private Investment Counsel',
        value: 'Scotia Private Investment Counsel',
    },
    { label: 'Scotia Securities Inc.', value: 'Scotia Securities Inc.' },
    {
        label: 'Scotia trust - The Bank of Nova Scotia Trust Company',
        value: 'Scotia trust - The Bank of Nova Scotia Trust Company',
    },
    { label: 'Scotia Wealth Management', value: 'Scotia Wealth Management' },
    {
        label: 'Scotiabank Advisor Deposit Services',
        value: 'Scotiabank Advisor Deposit Services',
    },
    {
        label: 'Seamark Asset Management Ltd.',
        value: 'Seamark Asset Management Ltd.',
    },
    { label: 'SECURIFONDS', value: 'SECURIFONDS' },
    {
        label: 'Secutor Capital Management Corp.',
        value: 'Secutor Capital Management Corp.',
    },
    { label: 'SEI funds', value: 'SEI funds' },
    { label: 'Sentry Investments', value: 'Sentry Investments' },
    { label: 'Servus Credit Union', value: 'Servus Credit Union' },
    { label: 'Seven Hills Capital Corp.', value: 'Seven Hills Capital Corp.' },
    {
        label: 'Seymour Investment Management Ltd',
        value: 'Seymour Investment Management Ltd',
    },
    { label: 'SFL Investments', value: 'SFL Investments' },
    { label: 'SGGG Funds', value: 'SGGG Funds' },
    {
        label: 'Sharp Asset Management Inc.',
        value: 'Sharp Asset Management Inc.',
    },
    {
        label: 'Shaunessy Investment Counsel Inc.',
        value: 'Shaunessy Investment Counsel Inc.',
    },
    {
        label: 'Sherbrooke Street Capital INC.',
        value: 'Sherbrooke Street Capital INC.',
    },
    {
        label: 'Silver Heights Capital Management Inc.',
        value: 'Silver Heights Capital Management Inc.',
    },
    {
        label: "Simplii Financial / President's Choice",
        value: "Simplii Financial / President's Choice",
    },
    {
        label: 'Skyon Financial Corporation',
        value: 'Skyon Financial Corporation',
    },
    { label: 'Slabe Inc.', value: 'Slabe Inc.' },
    {
        label: 'Slater Asset Management Inc',
        value: 'Slater Asset Management Inc',
    },
    { label: 'SOCIETE GENERALE', value: 'SOCIETE GENERALE' },
    { label: 'Solium Capital', value: 'Solium Capital' },
    {
        label: 'Soundvest Capital Management Ltd.',
        value: 'Soundvest Capital Management Ltd.',
    },
    { label: 'Spartan Fund Management', value: 'Spartan Fund Management' },
    { label: 'Sprott Private Wealth LP', value: 'Sprott Private Wealth LP' },
    {
        label: 'Sprung Investment Management Inc.',
        value: 'Sprung Investment Management Inc.',
    },
    { label: 'SSQ Life Insurance', value: 'SSQ Life Insurance' },
    { label: 'Standard Life', value: 'Standard Life' },
    {
        label: 'STEADYHAND INVESTMENT FUNDS INC.',
        value: 'STEADYHAND INVESTMENT FUNDS INC.',
    },
    { label: 'Steinbach Credit Union', value: 'Steinbach Credit Union' },
    {
        label: 'Stephen Avenue Securities Inc.',
        value: 'Stephen Avenue Securities Inc.',
    },
    { label: 'Sterling Mutual', value: 'Sterling Mutual' },
    {
        label: 'St-Mauris Gestion de Placements',
        value: 'St-Mauris Gestion de Placements',
    },
    {
        label: 'Stonebrooke Asset Management Ltd. (Rockvale)',
        value: 'Stonebrooke Asset Management Ltd. (Rockvale)',
    },
    {
        label: 'Stonehouse Capital Management Inc.',
        value: 'Stonehouse Capital Management Inc.',
    },
    {
        label: 'Stratigis Capital Advisors Inc.',
        value: 'Stratigis Capital Advisors Inc.',
    },
    {
        label: 'Stuart Investment Management',
        value: 'Stuart Investment Management',
    },
    {
        label: 'Successful Investor Wealth Management Inc.',
        value: 'Successful Investor Wealth Management Inc.',
    },
    {
        label: 'Summerhill Capital Management Inc.',
        value: 'Summerhill Capital Management Inc.',
    },
    {
        label: 'Summus Investment Management Inc.',
        value: 'Summus Investment Management Inc.',
    },
    { label: 'Sun Life Financial', value: 'Sun Life Financial' },
    { label: 'SunTrust Banks USA', value: 'SunTrust Banks USA' },
    {
        label: 'T.E. Investment Counsel Inc.',
        value: 'T.E. Investment Counsel Inc.',
    },
    { label: 'Tacita Capital Inc.', value: 'Tacita Capital Inc.' },
    { label: 'Tangerine', value: 'Tangerine' },
    { label: 'TCU Wealth Management', value: 'TCU Wealth Management' },
    { label: 'TD Ameritrade USA', value: 'TD Ameritrade USA' },
    { label: 'TD Canada Trust', value: 'TD Canada Trust' },
    { label: 'TD Direct Investing', value: 'TD Direct Investing' },
    { label: 'TD Future Builder', value: 'TD Future Builder' },
    { label: 'TD Mutual Funds', value: 'TD Mutual Funds' },
    {
        label: 'TD Share Ownership Equity Programs',
        value: 'TD Share Ownership Equity Programs',
    },
    { label: 'TD Waterhouse', value: 'TD Waterhouse' },
    { label: 'TD Wealth Management', value: 'TD Wealth Management' },
    {
        label: 'TD Wealth Private Investment Counsel',
        value: 'TD Wealth Private Investment Counsel',
    },
    {
        label: 'Tempered Investment Management Ltd.',
        value: 'Tempered Investment Management Ltd.',
    },
    { label: 'Tempest Capital Corp.', value: 'Tempest Capital Corp.' },
    {
        label: 'TenSquared Investments Inc.',
        value: 'TenSquared Investments Inc.',
    },
    {
        label: 'TFP Investment Counsel Corp.',
        value: 'TFP Investment Counsel Corp.',
    },
    {
        label: 'The Canadian Conference of Mennonite Brethren Churches',
        value: 'The Canadian Conference of Mennonite Brethren Churches',
    },
    {
        label: 'The Compagnie Monégasque de Banque',
        value: 'The Compagnie Monégasque de Banque',
    },
    { label: 'THE FAITHLIFE FINANCIAL', value: 'THE FAITHLIFE FINANCIAL' },
    {
        label: 'THE MANUFACTURERS LIFE INSURANCE COMPANY',
        value: 'THE MANUFACTURERS LIFE INSURANCE COMPANY',
    },
    {
        label: 'The Murray Wealth Group Inc.',
        value: 'The Murray Wealth Group Inc.',
    },
    {
        label: 'Thornmark Asset Management Inc.',
        value: 'Thornmark Asset Management Inc.',
    },
    { label: 'Tower Asset Management', value: 'Tower Asset Management' },
    {
        label: 'Transition Financial Advisors Group, Inc.',
        value: 'Transition Financial Advisors Group, Inc.',
    },
    {
        label: 'Trestle Asset Management Inc.',
        value: 'Trestle Asset Management Inc.',
    },
    { label: 'Triasima', value: 'Triasima' },
    {
        label: 'Triasima Portfolio Management Inc.',
        value: 'Triasima Portfolio Management Inc.',
    },
    {
        label: 'TriDelta Investment Management Inc.',
        value: 'TriDelta Investment Management Inc.',
    },
    {
        label: 'Triumph Asset Management Inc.',
        value: 'Triumph Asset Management Inc.',
    },
    { label: 'TRUST ETERNA INC', value: 'TRUST ETERNA INC' },
    {
        label: 'Tulett Mathews Associates Inc.',
        value: 'Tulett Mathews Associates Inc.',
    },
    { label: 'Turn8 Partners Inc.', value: 'Turn8 Partners Inc.' },
    {
        label: 'Turnpoint Wealth Management',
        value: 'Turnpoint Wealth Management',
    },
    {
        label: 'Turtle Creek Asset Management Inc.',
        value: 'Turtle Creek Asset Management Inc.',
    },
    { label: 'UBS Bank (Canada)', value: 'UBS Bank (Canada)' },
    { label: 'UBS Bank USA', value: 'UBS Bank USA' },
    {
        label: 'Ullman Wealth Management Inc',
        value: 'Ullman Wealth Management Inc',
    },
    { label: 'UNI Financial Cooperation', value: 'UNI Financial Cooperation' },
    { label: 'Union Life Insurance', value: 'Union Life Insurance' },
    {
        label: 'USA - RBC Wealth Management',
        value: 'USA - RBC Wealth Management',
    },
    {
        label: 'Value Contrarian Asset Management Inc.',
        value: 'Value Contrarian Asset Management Inc.',
    },
    {
        label: 'Value Partners Investments Inc.',
        value: 'Value Partners Investments Inc.',
    },
    { label: 'Value Sciences Inc.', value: 'Value Sciences Inc.' },
    {
        label: 'Vancity Savings Credit Union',
        value: 'Vancity Savings Credit Union',
    },
    {
        label: 'Vantage Point Investment Management Inc.',
        value: 'Vantage Point Investment Management Inc.',
    },
    {
        label: 'Venable Park Investment Counsel Inc.',
        value: 'Venable Park Investment Counsel Inc.',
    },
    {
        label: 'Venator Capital Management Ltd.',
        value: 'Venator Capital Management Ltd.',
    },
    {
        label: 'Veritas Investment Research Corporation',
        value: 'Veritas Investment Research Corporation',
    },
    {
        label: 'VERTEX FUND - Vertex One Asset Management',
        value: 'VERTEX FUND - Vertex One Asset Management',
    },
    {
        label: 'Vertex One Asset Management Ltd.',
        value: 'Vertex One Asset Management Ltd.',
    },
    {
        label: 'Vestcap Investment Management Inc.',
        value: 'Vestcap Investment Management Inc.',
    },
    { label: 'Viking Capital Corporation', value: 'Viking Capital Corporation' },
    { label: 'Virtual Brokers', value: 'Virtual Brokers' },
    {
        label: 'Visavis Investment Counsel Inc.',
        value: 'Visavis Investment Counsel Inc.',
    },
    {
        label: 'W. Shupe Company Investment Advisory Services Inc.',
        value: 'W. Shupe Company Investment Advisory Services Inc.',
    },
    {
        label: 'W.A. Robinson Asset Management Ltd.',
        value: 'W.A. Robinson Asset Management Ltd.',
    },
    { label: 'W.D. Latimer Co. Ltd', value: 'W.D. Latimer Co. Ltd' },
    {
        label: 'Waratah Capital Advisors Ltd.',
        value: 'Waratah Capital Advisors Ltd.',
    },
    {
        label: 'Waterstreet Family Capital Counsel Inc.',
        value: 'Waterstreet Family Capital Counsel Inc.',
    },
    {
        label: 'Watson Di Primio Steel Investment Management Ltd.',
        value: 'Watson Di Primio Steel Investment Management Ltd.',
    },
    { label: 'Watt Carmichael INC.', value: 'Watt Carmichael INC.' },
    { label: 'Wawanesa', value: 'Wawanesa' },
    {
        label: 'WealthBar Financial Services Inc.',
        value: 'WealthBar Financial Services Inc.',
    },
    {
        label: 'Wealthbridge Investment Counsel Inc.',
        value: 'Wealthbridge Investment Counsel Inc.',
    },
    {
        label: 'WealthCo Asset Management Inc.',
        value: 'WealthCo Asset Management Inc.',
    },
    { label: 'Wealthsimple Inc.', value: 'Wealthsimple Inc.' },
    {
        label: 'Wellington Altus Private Wealth',
        value: 'Wellington Altus Private Wealth',
    },
    {
        label: 'Wells Asset Management System Inc.',
        value: 'Wells Asset Management System Inc.',
    },
    { label: 'Wells Fargo Canada', value: 'Wells Fargo Canada' },
    { label: 'Wells Fargo USA', value: 'Wells Fargo USA' },
    {
        label: 'Western Pacific Trust Company',
        value: 'Western Pacific Trust Company',
    },
    { label: 'Whitehaven Securities Inc.', value: 'Whitehaven Securities Inc.' },
    {
        label: 'Wickham Investment Counsel Inc.',
        value: 'Wickham Investment Counsel Inc.',
    },
    {
        label: 'Windcroft Financial Counsel Limited',
        value: 'Windcroft Financial Counsel Limited',
    },
    {
        label: 'Wise Capital Management Inc.',
        value: 'Wise Capital Management Inc.',
    },
    { label: 'WORKING OPPORTUNITY FUND', value: 'WORKING OPPORTUNITY FUND' },
    {
        label: 'Worldsource Financial Management',
        value: 'Worldsource Financial Management',
    },
    { label: 'Worldsource Securities', value: 'Worldsource Securities' },
    {
        label: 'Wutherich Company Investment Counsel Inc.',
        value: 'Wutherich Company Investment Counsel Inc.',
    },
    {
        label: 'Yorkville Asset Management Inc.',
        value: 'Yorkville Asset Management Inc.',
    },
    { label: 'OTHER', value: 'OTHER' },
];
