on: [push]

jobs:
    lint-build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repo
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Install deps
              run: |
                  npm install
            - name: Lint and build project into dist
              run: |
                  npm run build
